CREATE DATABASE MANAGER;

USE MANAGER

CREATE TABLE EMPLOYEES (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(50) NOT NULL,
  POSITION VARCHAR(50) DEFAULT NULL,
  MANAGER INT(11) DEFAULT NULL,
  PRIMARY KEY(ID),
  CONSTRAINT FK_MANAGER
    FOREIGN KEY(MANAGER) REFERENCES EMPLOYEES(ID)
    ON DELETE SET NULL
    ON UPDATE CASCADE
);
